### ISSUE TITLE
Issue with join

### ISSUE THREAD

**Issue by raiviskrumins** [dalibo/ldap2pg#172]
I was using configuration provided in https://github.com/dalibo/ldap2pg/issues/128#issuecomment-347879982, but I got result:
```[ldap2pg.script      ERROR] Unhandled error:
[ldap2pg.script      ERROR] Traceback (most recent call last):
[ldap2pg.script      ERROR]   File "/home/raivis/virtualEnvs/ldap2pg/lib/python3.5/site-packages/ldap2pg/script.py", line 79, in main
[ldap2pg.script      ERROR]     exit(wrapped_main(config))
[ldap2pg.script      ERROR]   File "/home/raivis/virtualEnvs/ldap2pg/lib/python3.5/site-packages/ldap2pg/script.py", line 59, in wrapped_main
[ldap2pg.script      ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script      ERROR]   File "/home/raivis/virtualEnvs/ldap2pg/lib/python3.5/site-packages/ldap2pg/manager.py", line 375, in sync
[ldap2pg.script      ERROR]     ldaproles, ldapacls = self.inspect_ldap(syncmap)
[ldap2pg.script      ERROR]   File "/home/raivis/virtualEnvs/ldap2pg/lib/python3.5/site-packages/ldap2pg/manager.py", line 256, in inspect_ldap
[ldap2pg.script      ERROR]     entries = self.query_ldap(**mapping['ldap'])
[ldap2pg.script      ERROR] TypeError: query_ldap() got an unexpected keyword argument 'join'
[ldap2pg.script      ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
```

Is `join` still supported?
Maybe there is another way to get members `sAMAccountName`?

**Comment by bersace** [comment]
Hi,

`join` is not (yet) supported. If you read carefully the comment, it's a `mock`.

For now, the way to go is `memberOf` which requires to known the groups you want to query. see  https://github.com/dalibo/ldap2pg/issues/128#issuecomment-347887563 in the same issue.

**Comment by raiviskrumins** [comment]
OK, thank you for clarification
