### ISSUE TITLE
UnicodeDecodeError when using sync_map.ldap and Python 2.7.13

### ISSUE THREAD

**Issue by jrjsmrtn** [dalibo/ldap2pg#225]
The following ldap2pg.yml is working fine with Python 2.7.13 on Debian 9.4 (see attached ldap2pg.success.log for details):

```
verbose: on

ldap:
  uri: ldap://localhost:389/

postgres:
  managed_roles_query: |
    SELECT rolname
    FROM pg_catalog.pg_roles
    WHERE
        (rolsuper IS FALSE)
        AND (rolname NOT IN ('xxx-admin'))
    ORDER BY 1;

sync_map:
- roles:
  - name: role1
    options: NOLOGIN
  - name: role2
    option: NOLOGIN
```

But whenever I add ldap entries to the sync_map:

```
sync_map:
- roles:
  - name: role1
    options: NOLOGIN
  - name: role2
    option: NOLOGIN
- ldap:
    base: dc=cxptc,dc=org
  role:
    name_attribute: sAMAccountName
    options: LOGIN
```

I get this:
```
[...]
Querying LDAP dc=cxptc,dc=org... (objectClass...
Doing: ldapsearch -x -D  -b dc=cxptc,dc=org -s sub '(objectClass=*)' 
Unhandled error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/script.py", line 84, in main
    exit(wrapped_main(config))
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/script.py", line 68, in wrapped_main
    count = manager.sync(syncmap=config['sync_map'])
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/manager.py", line 188, in sync
    ldaproles, ldapacl = self.inspect_ldap(syncmap)
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/manager.py", line 127, in inspect_ldap
    entries = self.query_ldap(**mapping['ldap'])
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/manager.py", line 37, in query_ldap
    base, scope, filter, attributes,
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/ldap.py", line 161, in search_s
    return self.wrapped.search_s(base, scope, filter, attributes)
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/ldap.py", line 132, in __call__
    return decode_value(self.callable_(*a, **kw))
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/utils.py", line 86, in decode_value
    return [decode_value(v) for v in value]
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/utils.py", line 88, in decode_value
    return tuple([decode_value(v) for v in value])
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/utils.py", line 83, in decode_value
    for k, v in value.items()
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/utils.py", line 86, in decode_value
    return [decode_value(v) for v in value]
  File "/usr/local/lib/python2.7/dist-packages/ldap2pg/utils.py", line 79, in decode_value
    return value.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 5: invalid start byte
```

The logs for successful and failed runs are attached:
[ldap2pg.fail.log](https://github.com/dalibo/ldap2pg/files/2144639/ldap2pg.fail.log)
[ldap2pg.success.log](https://github.com/dalibo/ldap2pg/files/2144640/ldap2pg.success.log)

My config is: ldap2pg 4.10 from git master, psycopg2 2.6.2, python-ldap 2.4.28 and Python 2.7.13 on Debian 9.4. LDAP (Samba AD DC 4.8.2-debian) and PostgreSQL (9.6.7) are on the same host and anonymous LDAP searches are enabled.

I tried with Python 3.5.3 but encountered another issue: #224

**Comment by bersace** [comment]
hi,

Looks like `ldap2pg` wants to decode a binary value.

Can you try `name: '{sAMAccountName}' instead of `name_attribute` ?

**Comment by bersace** [comment]
Can you send me the LDIF of the first entry returned by `ldapsearch -x -D  -b dc=cxptc,dc=org -s sub '(objectClass=*)' ` I would like to reproduce so that `ldap2pg` does at least show a better error message.

**Comment by jrjsmrtn** [comment]
Hmmm...

`ldapsearch -x -D -b dc=cxptc,dc=org -s sub '(objectClass=*)'` fails:

```
ldap_bind: Strong(er) authentication required (8)
        additional info: BindSimple: Transport encryption required.
```

...which is why I set up LDAP anonymous searches and `ldapsearch -x -b dc=cxptc,dc=org -s sub '(objectClass=*)'` works with no _-D binddn_.

**Comment by bersace** [comment]
@jrjsmrtn yes, `ldap2pg` is naïve and should not put `-D`. Can you send me the LDAP entry with binary attribute ?

**Comment by bersace** [comment]
I'm not happy that `ldapsearch` has no attributes argument. `ldap2pg` should not request all attributes, it's a waste and cause such errors.

**Comment by jrjsmrtn** [comment]
Here is the first (anonymized) entry returned by ldapsearch:

```
# extended LDIF
#
# LDAPv3
# base <cn=Users,dc=cxptc,dc=org> with scope subtree
# filter: (sAMAccountName=*)
# requesting: ALL
#

# Some User, Users, cxptc.org
dn: CN=Some User,CN=Users,DC=cxptc,DC=org
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: Some User
sn: User
givenName: Some
instanceType: 4
whenCreated: 20180627120904.0Z
whenChanged: 20180627120904.0Z
displayName: Some User
uSNCreated: 3563
uSNChanged: 3563
name: Some User
objectGUID:: j3PS7+faUk+qrmanbvUWIg==
userAccountControl: 512
codePage: 0
countryCode: 0
pwdLastSet: 131745749448423910
primaryGroupID: 513
objectSid:: AQUAAAAAAAUVAAAA1WFT3/1k61CS5dbRYwQAAA==
accountExpires: 9223372036854775807
sAMAccountName: someuser
sAMAccountType: 805306368
userPrincipalName: someuser@cxptc.org
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=cxptc,DC=org
uid: someuser
msSFU30Name: someuser
msSFU30NisDomain: CXPTC
uidNumber: 200015
gidNumber: 100000
gecos: Some User
unixHomeDirectory: /home/CXPTC/someuser
loginShell: /bin/bash
memberOf: CN=somegroup,CN=Groups,DC=cxptc,DC=org
memberOf: CN=anothergroup,CN=Groups,DC=cxptc,DC=org
distinguishedName: CN=Some User,CN=Users,DC=cxptc,DC=org

```

**Comment by jrjsmrtn** [comment]
I have the same issue with `name: '{sAMAccountName}'`, btw.

**Comment by cbandy** [comment]
Is that output from the same query? 🤔 I see `filter: (sAMAccountName=*)`.

**Comment by bersace** [comment]
I think this is this attributes.

``` ldif
objectGUID:: j3PS7+faUk+qrmanbvUWIg==
objectSid:: AQUAAAAAAAUVAAAA1WFT3/1k61CS5dbRYwQAAA==
```

**Comment by bersace** [comment]
@jrjsmrtn Can you give me the attributeType of `objectSid` ? I don't find a schema on this.

**Comment by bersace** [comment]
@cbandy I see `sAMAccountName: someuser`, that should do the job.

**Comment by bersace** [comment]
@jrjsmrtn just a side note, you can put multiple names in a single `roles` entry.

``` yaml
sync_map:
- roles:
  - names:
    - role1
    - role2
    options: NOLOGIN

```

**Comment by bersace** [comment]
Putting `sAMAccountName` instead of `cn` still works. Only `sAMAccountName` is queried.

```
[ldap2pg.manager      DEBUG] Found role role2 from YAML.
[ldap2pg.manager       INFO] Querying LDAP ou=people,dc=ldap,dc=lda... (cn=*)...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D cn=admin,dc=ldap,dc=ldap2pg,dc=docker -W -b ou=people,dc=ldap,dc=ldap2pg,dc=docker -s sub '(cn=*)' sAMAccountName
[ldap2pg.manager      DEBUG] Got 14 entries from LDAP.
```

**Comment by bersace** [comment]
@jrjsmrtn ok, that looks like a bug with Python 2.7 only.

**Comment by bersace** [comment]
@jrjsmrtn can you try master ? This should be fixed.

**Comment by jrjsmrtn** [comment]
@bersace the syntax of the [objectSid attribute](https://docs.microsoft.com/en-us/windows/desktop/ADSchema/a-objectsid) is "[String(Sid)](https://docs.microsoft.com/en-us/windows/desktop/ADSchema/s-string-sid)". They are both part of the [ActiveDirectory schema](https://docs.microsoft.com/en-us/windows/desktop/ADSchema/active-directory-schema). More about SIDs [here](https://docs.microsoft.com/en-us/windows/desktop/SecAuthZ/sid-components).

**Comment by jrjsmrtn** [comment]
@cbandy: yes, sorry, I may have changed the query in the meantime because of #224

**Comment by jrjsmrtn** [comment]
@bersace: I tested the git master with the sAMAccountName and userPrincipalName attributes: it's working fine ! Thanks a lot for your help :-)

**Comment by bersace** [comment]
@jrjsmrtn nice. 4.11 is on PyPI with the fix ! Thanks for the report !

```
running upload
Submitting dist/ldap2pg-4.11.tar.gz to https://upload.pypi.org/legacy/
Server response (200): OK
Submitting /home/bersace/src/dalibo/ldap2pg/dist/ldap2pg-4.11-py2.py3-none-any.whl to https://upload.pypi.org/legacy/
Server response (200): OK
```
