### ISSUE TITLE
Fails to discard LDAP search references

### ISSUE THREAD

**Issue by zurikus** [dalibo/ldap2pg#270]
Hello Étienne Bersac,

I'm facing one issue with ldap2pg package and I hope you can help to solve it.
So, I have several OU in my LDAP structure: 
Every OU have own Groups and users.

So, I place one of users from different OU to group of other OU and configured LDAP search in this way:

```
...
- ldap:
    base: dc=f10,dc=cloud
    scope: sub
    filter: |
      (&
      (objectClass=User)
      (memberOf=cn=psql-acl-local-bi-ro,ou=groups,ou=.f100,dc=f10,dc=cloud)
      )
  role:
    name_attribute: sAMAccountName
    options: LOGIN
    parent:
    - ldap_roles
    - acl_local_bi_ro
    comment: "Managed by LDAP"
...
```

When I make run I'm getting error: 

```
[ldap2pg.manager       INFO] Querying LDAP dc=f10,dc=cloud... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D cn=pgadsync,cn=Users,dc=f10,dc=cloud -W -b dc=f10,dc=cloud -s sub '(&
[ldap2pg.ldap         DEBUG] (objectClass=User)
[ldap2pg.ldap         DEBUG] (memberOf=cn=psql-acl-local-bi-ro,ou=groups,ou=.f100,dc=f10,dc=cloud)
[ldap2pg.ldap         DEBUG] )' sAMAccountName
[ldap2pg.manager      DEBUG] Got 5 entries from LDAP.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 94, in main
[ldap2pg.script       ERROR]     exit(wrapped_main(config))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 70, in wrapped_main
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/manager.py", line 215, in sync
[ldap2pg.script       ERROR]     ldaproles, ldapacl = self.inspect_ldap(syncmap)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/manager.py", line 154, in inspect_ldap
[ldap2pg.script       ERROR]     entries = self.query_ldap(**mapping['ldap'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/manager.py", line 46, in query_ldap
[ldap2pg.script       ERROR]     attributes['dn'] = [dn]
[ldap2pg.script       ERROR] TypeError: list indices must be integers or slices, not str
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to libpq default.

```
When I run this query manually it is working fine for me: 

```
$ ldapsearch -H ldap://ldap-test.f10.cloud -x -W -D "pgadsync" -b "dc=f10,dc=cloud" -s sub "(&(objectClass=User)(memberOf=cn=psql-acl-local-bi-ro,ou=groups,ou=.f100,dc=f10,dc=cloud))" sAMAccountName
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <dc=f10,dc=cloud> with scope subtree
# filter: (&(objectClass=User)(memberOf=cn=psql-acl-local-bi-ro,ou=groups,ou=.f100,dc=f10,dc=cloud))
# requesting: sAMAccountName
#

# Some user 1, users, .f100, f10.cloud
dn: CN=Some user 1,OU=users,OU=.f100,DC=f10,DC=cloud
sAMAccountName: xx582hj

# Some user 2, users, .f101, f10.cloud
dn: CN=Some user 2,OU=users,OU=.f101,DC=f10,DC=cloud
sAMAccountName: ME335OH

# search reference
ref: ldap://ForestDnsZones.f10.cloud/DC=ForestDnsZones,DC=f10,DC=cloud

# search reference
ref: ldap://DomainDnsZones.f10.cloud/DC=DomainDnsZones,DC=f10,DC=cloud

# search reference
ref: ldap://f10.cloud/CN=Configuration,DC=f10,DC=cloud

# search result
search: 2
result: 0 Success

# numResponses: 6
# numEntries: 2
# numReferences: 3

```

Could you take a look what is happening here?

**Comment by bersace** [comment]
Hi @zurikus , can you reproduce with `DEBUG=1 ldap2pg ...` and type `pp attributes` in the debugger ? Then paste it here. Thanks.

**Comment by zurikus** [comment]
Yes, sure

```
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 94, in main
[ldap2pg.script       ERROR]     exit(wrapped_main(config))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/script.py", line 70, in wrapped_main
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/manager.py", line 215, in sync
[ldap2pg.script       ERROR]     ldaproles, ldapacl = self.inspect_ldap(syncmap)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/manager.py", line 154, in inspect_ldap
[ldap2pg.script       ERROR]     entries = self.query_ldap(**mapping['ldap'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.5/dist-packages/ldap2pg/manager.py", line 46, in query_ldap
[ldap2pg.script       ERROR]     attributes['dn'] = [dn]
[ldap2pg.script       ERROR] TypeError: list indices must be integers or slices, not str
[ldap2pg.script       DEBUG] Dropping in debugger.
> /usr/local/lib/python3.5/dist-packages/ldap2pg/manager.py(46)query_ldap()
-> attributes['dn'] = [dn]
(Pdb) pp attributes
['ldap://ForestDnsZones.f10.cloud/DC=ForestDnsZones,DC=f10,DC=cloud']
(Pdb) pp raw_entries
[('CN=Some User 1,OU=users,OU=.f100,DC=f10,DC=cloud',
  {'dn': ['CN=Some User 1,OU=users,OU=.f100,DC=f10,DC=cloud'],
   'sAMAccountName': [b'xx582hj']}),
 ('CN=Some User 2,OU=users,OU=.f101,DC=f10,DC=cloud',
  {'dn': ['CN=Some User 2,OU=users,OU=.f101,DC=f10,DC=cloud'],
   'sAMAccountName': [b'ME335OH']}),
 (None, ['ldap://ForestDnsZones.f10.cloud/DC=ForestDnsZones,DC=f10,DC=cloud']),
 (None, ['ldap://DomainDnsZones.f10.cloud/DC=DomainDnsZones,DC=f10,DC=cloud']),
 (None, ['ldap://f10.cloud/CN=Configuration,DC=f10,DC=cloud'])]
(Pdb)

```

**Comment by bersace** [comment]
Thansk @zurikus ! Can you build a LDAP query that do not returns refs ? Try with ldapsearch. That would workaround the bug.

By the way, i'll fix ldap2pg to discard refs.

**Comment by bersace** [comment]
@zurikus which version of ldap2pg do you run ?

**Comment by zurikus** [comment]
Ldap search without search references.

```
$ ldapsearch -H ldap://ldap-test.f10.cloud -x -W -D "pgadsync" -b "OU=users,OU=.f100,dc=f10,dc=cloud" "(memberOf=cn=psql-acl-local-bi-ro,ou=groups,ou=.f100,DC=f10,DC=cloud)" sAMAccountName
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <OU=users,OU=.f100,dc=f10,dc=cloud> with scope subtree
# filter: (memberOf=cn=psql-acl-local-bi-ro,ou=groups,ou=.f100,DC=f10,DC=cloud)
# requesting: sAMAccountName
#

# Some User 1, users, .f100, f10.cloud
dn: CN=Some User 1,OU=users,OU=.f100,DC=f10,DC=cloud
sAMAccountName: xx582hj

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

```

**Comment by zurikus** [comment]
$ ldap2pg -V
ldap2pg 4.17
psycopg2 2.7.6.1 (dt dec pq3 ext lo64)
python-ldap 3.1.0
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]

**Comment by bersace** [comment]
Ok. I released 4.18. Can you test it ? You can close if you're ok.

**Comment by zurikus** [comment]
Ueee, thank you very much, looks great now:

$ ldap2pg -V
ldap2pg 4.18
psycopg2 2.7.6.1 (dt dec pq3 ext lo64)
python-ldap 3.1.0
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]


```
[ldap2pg.manager       INFO] Querying LDAP dc=f10,dc=cloud... (&(objectCla...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -x -D cn=pgadsync,cn=Users,dc=f10,dc=cloud -W -b dc=f10,dc=cloud -s sub '(&
[ldap2pg.ldap         DEBUG] (objectClass=User)
[ldap2pg.ldap         DEBUG] (memberOf=cn=psql-acl-local-bi-ro,ou=groups,ou=.f100,dc=f10,dc=cloud)
[ldap2pg.ldap         DEBUG] )' sAMAccountName
[ldap2pg.manager      DEBUG] Got 5 entries from LDAP.
[ldap2pg.manager      DEBUG] Discarding ref: ['ldap://ForestDnsZones.f10.cloud/DC=For.
[ldap2pg.manager      DEBUG] Discarding ref: ['ldap://DomainDnsZones.f10.cloud/DC=Dom.
[ldap2pg.manager      DEBUG] Discarding ref: ['ldap://f10.cloud/CN=Configuration,DC=f.
[ldap2pg.manager      DEBUG] Found role xx582hj from CN=Some User 1,OU=users,OU=.f100,DC=f10,DC=cloud.
[ldap2pg.manager      DEBUG] Role xx582hj is member of ldap_roles, acl_local_bi_ro.
[ldap2pg.manager      DEBUG] Found role me335oh from CN=Some User 2,OU=users,OU=.f101,DC=f10,DC=cloud.
[ldap2pg.manager      DEBUG] Role me335oh is member of ldap_roles, acl_local_bi_ro.

```

Thank you very much!!!

**Comment by bersace** [comment]
You're welcome ! :+1:
