### ISSUE TITLE
Exception on blacklist query

### ISSUE THREAD

**Issue by alehaa** [dalibo/ldap2pg#399]
## ldap2pg.yml

<details><summary>ldap2pg.yml</summary>

``` yaml
roles_blacklist_query: |
  SELECT login FROM myusertable;

sync_map:
- role:
    names:
      - foo
      - bar
    options: LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE
```
</details>

## Expectations

`ldap2pg` should execute the query and use its returned rows as blacklist. Instead it raises an exception.

## Verbose output of ldap2pg execution

<details><summary>Verbose output</summary>

``` console
$ ldap2pg -n -c ldap2pg.yml --verbose
[ldap2pg.config        INFO] Starting ldap2pg 5.7.
[ldap2pg.config       DEBUG] Trying ldap2pg.yml.
[ldap2pg.config        INFO] Using /somepath/ldap2pg.yml.
[ldap2pg.config       DEBUG] Read dry from argv.
[ldap2pg.config       DEBUG] Read verbosity from argv.
[ldap2pg.config       DEBUG] Read postgres:roles_blacklist_query from YAML.
[ldap2pg.config       DEBUG] Read sync_map from YAML.
[ldap2pg.config       DEBUG] Drop unused hidden privilege __connect__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __create_on_schemas__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_delete_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_insert_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_references_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_select_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_trigger_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_truncate_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_update_on_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_usage_on_types__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __delete_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __execute_on_all_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __global_default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __insert_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __references_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __select_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __temporary__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __trigger_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __truncate_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __update_on_all_tables__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_all_sequences__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __usage_on_schemas__
[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.script       WARNI] Running in dry mode. Postgres will be untouched.
[ldap2pg.psql         DEBUG] Connecting to Postgres libpq default.
[ldap2pg.script       DEBUG] Inspecting role attributes.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT array_agg(attrs.attname)
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_namespace AS nsp
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_class AS tables
[ldap2pg.psql         DEBUG]   ON tables.relnamespace = nsp.oid AND tables.relname = 'pg_authid'
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_attribute AS attrs
[ldap2pg.psql         DEBUG]   ON attrs.attrelid = tables.oid AND attrs.attname LIKE 'rol%'
[ldap2pg.psql         DEBUG] WHERE nsp.nspname = 'pg_catalog'
[ldap2pg.psql         DEBUG] ORDER BY 1
[ldap2pg.role         DEBUG] Postgres server supports role options BYPASSRLS, LOGIN, CREATEDB, CREATEROLE, INHERIT, REPLICATION, SUPERUSER.
[ldap2pg.manager       INFO] Inspecting roles in Postgres cluster...
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/script.py", line 37, in main
[ldap2pg.script       ERROR]     exit(synchronize(config))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/script.py", line 130, in synchronize
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/manager.py", line 278, in sync
[ldap2pg.script       ERROR]     self.inspector.roles_blacklist = self.inspector.fetch_roles_blacklist()
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/inspector.py", line 226, in fetch_roles_blacklist
[ldap2pg.script       ERROR]     return self.fetch(self.psql, 'roles_blacklist_query', self.row1)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/inspector.py", line 188, in fetch
[ldap2pg.script       ERROR]     rows = list(self.timer.time_iter(rows))
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/utils.py", line 185, in time_iter
[ldap2pg.script       ERROR]     item = next(iterator)
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/inspector.py", line 58, in row1
[ldap2pg.script       ERROR]     for row in handle_decoding_error(rows):
[ldap2pg.script       ERROR]   File "/usr/local/lib/python3.9/dist-packages/ldap2pg/inspector.py", line 324, in handle_decoding_error
[ldap2pg.script       ERROR]     for item in iterator:
[ldap2pg.script       ERROR] TypeError: 'PSQLSession' object is not iterable
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to libpq default.
```
</details>

**Comment by bersace** [comment]
Hi @alehaa , sorry for the late answer. I missed the notification.

Why is the query not in `postgres:` block ?

``` yaml
postgres:
  roles_blacklist_query: |
    SELECT ...
```

**Comment by bersace** [comment]
Ok, I reproduced.

**Comment by alehaa** [comment]
Thanks for fixing! :)
