### ISSUE TITLE
Connecting to local postgresql database using the "peer" / SSO method runs in error

### ISSUE THREAD

**Issue by arjan-saly-tfs** [dalibo/ldap2pg#415]
### The whole picture
On my Linux/PostgreSQL server, I have a dedicated linux user (`ldap2pg`) to schedule and run ldap2pg.
This user also exist as a connect-role in my database. As both user and database are on the same server, I specify "peer" as an allowed  connection method for this user in pg_hab.conf:
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             ldap2pg                                 peer
```

This way, I don't have to specify a user or password when trying to connect when logged in on Linux as user `ldap2pg`, which makes distribution across servers (DTAP) a lot easier.

The fact that this works on the PostgreSQL side can be proven as this linux command succeeds (not specifying userid and password):
```
$ psql -d postgres
psql (12.11 (Ubuntu 12.11-1.pgdg18.04+1))
Type "help" for help.

postgres=#
```

As per [PostgreSQL documentation](https://www.postgresql.org/docs/12/libpq-connect.html#:~:text=postgresql%3A//%5Buserspec%40%5D%5Bhostspec%5D%5B/dbname%5D%5B%3Fparamspec%5D
), specifying userid and password are optional in the postgres-connect string: 
```
postgresql://[userspec@][hostspec][/dbname][?paramspec]
```

With this in mind, I placed this connect string in the ldap2pg.yml file, in the `postgres:` section, expecting it to work:
```
postgres:
  dsn: postgresql://localhost:5432/postgres
```

Unfortunately, it doesn't, returning a connection error. However, when trying to connect with this string using `psql`, I'm asked for a password. Not as expected and mentioned as such on several (other) github threads. 

### The real issue
These github threads though, showed that this this can easily be solved by removing the whole host specification.

This psql command works fine indeed, without specifying any userid or password:
```
$ psql  postgresql:///postgres
psql (12.11 (Ubuntu 12.11-1.pgdg18.04+1))
Type "help" for help.

postgres=>
```

However, when I place this connect string into my ldap2pg.yml file:
```
postgres:
  dsn: postgresql:///postgres
```

I run in this error:
```
[ldap2pg.psql         DEBUG] Connecting to Postgres postgresql:postgres.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/script.py", line 37, in main
[ldap2pg.script       ERROR]     exit(synchronize(config))
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/script.py", line 130, in synchronize
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/manager.py", line 312, in sync
[ldap2pg.script       ERROR]     schemas = self.inspector.fetch_schemas(databases, ldaproles)
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/inspector.py", line 233, in fetch_schemas
[ldap2pg.script       ERROR]     for dbname, psql in self.psql.itersessions(databases):
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/psql.py", line 86, in itersessions
[ldap2pg.script       ERROR]     with self(dbname) as session:
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/psql.py", line 156, in __enter__
[ldap2pg.script       ERROR]     self.conn = psycopg2.connect(self.connstring)
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/psycopg2/__init__.py", line 126, in connect
[ldap2pg.script       ERROR]     dsn = _ext.make_dsn(dsn, **kwargs)
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/psycopg2/extensions.py", line 153, in make_dsn
[ldap2pg.script       ERROR]     parse_dsn(dsn)
[ldap2pg.script       ERROR] ProgrammingError: invalid dsn: missing "=" after "postgresql:postgres" in connection info string
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to postgresql:///postgres.
```

The full verbose output (see below) shows that ldap2pg does successfully connect to the PostgreSQL database and executes SELECT statements. So this uri is accepted for some parts of the process, but fails on another part. 

Can you please take a look at this and try to solve?

Thanks!

### Full verbose output
```
$ VERBOSITY=DEBUG ldap2pg --config ldap2pg.yml
[ldap2pg.config       DEBUG] Processing CLI arguments.
[ldap2pg.config        INFO] Starting ldap2pg 5.7.
[ldap2pg.config       DEBUG] Trying ldap2pg.yml.
[ldap2pg.config        INFO] Using /home/ldap2pg/ldap2pg.yml.
[ldap2pg.config       DEBUG] Read verbosity from argv.
[ldap2pg.config       DEBUG] Read version from YAML.
[ldap2pg.config       DEBUG] Read ldap:uri from YAML.
[ldap2pg.config       DEBUG] Read ldap:user from YAML.
[ldap2pg.config       DEBUG] Read ldap:password from YAML.
[ldap2pg.config       DEBUG] Read postgres:dsn from YAML.
[ldap2pg.config       DEBUG] Read postgres:databases_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:owners_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:managed_roles_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:roles_blacklist_query from YAML.
[ldap2pg.config       DEBUG] Read postgres:schemas_query from YAML.
[ldap2pg.config       DEBUG] Read privileges from YAML.
[ldap2pg.config       DEBUG] Read sync_map from YAML.
[ldap2pg.config       DEBUG] Drop unused hidden privilege __default_execute_on_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __execute_on_all_functions__
[ldap2pg.config       DEBUG] Drop unused hidden privilege __global_default_execute_on_functions__
[ldap2pg.config       DEBUG] Configuration loaded.
[ldap2pg.script       DEBUG] Setting up LDAP client.
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: u'/etc/openldap/ldap.conf'
[ldap2pg.ldap         DEBUG] Found rcfile /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Read TLS_CACERT from /etc/ldap/ldap.conf.
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: u'/home/ldap2pg/ldaprc'
[ldap2pg.ldap         DEBUG] Ignoring: [Errno 2] No such file or directory: u'/home/ldap2pg/.ldaprc'
[ldap2pg.ldap         DEBUG] Read URI from YAML.
[ldap2pg.ldap         DEBUG] Read USER from YAML.
[ldap2pg.ldap         DEBUG] Read PASSWORD from YAML.
[ldap2pg.ldap         DEBUG] Connecting to LDAP server ldap://company.com.
[ldap2pg.ldap         DEBUG] Trying SASL DIGEST-MD5 auth.
[ldap2pg.ldap         DEBUG] Authenticating: ldapwhoami -Y DIGEST-MD5 -U 'ad-user' -W
[ldap2pg.script       WARNI] Running in dry mode. Postgres will be untouched.
[ldap2pg.psql         DEBUG] Connecting to Postgres postgresql:///postgres.
[ldap2pg.script       DEBUG] Inspecting role attributes.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT array_agg(attrs.attname)
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_namespace AS nsp
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_class AS tables
[ldap2pg.psql         DEBUG]   ON tables.relnamespace = nsp.oid AND tables.relname = 'pg_authid'
[ldap2pg.psql         DEBUG] JOIN pg_catalog.pg_attribute AS attrs
[ldap2pg.psql         DEBUG]   ON attrs.attrelid = tables.oid AND attrs.attname LIKE 'rol%'
[ldap2pg.psql         DEBUG] WHERE nsp.nspname = 'pg_catalog'
[ldap2pg.psql         DEBUG] ORDER BY 1
[ldap2pg.role         DEBUG] Postgres server supports role options BYPASSRLS, LOGIN, CREATEDB, CREATEROLE, INHERIT, REPLICATION, SUPERUSER.
[ldap2pg.manager       INFO] Inspecting roles in Postgres cluster...
[ldap2pg.psql         DEBUG] Using Postgres connection to postgresql:///postgres.
[ldap2pg.inspector    DEBUG] Introspecting session Postgres role.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT current_user, rolsuper
[ldap2pg.psql         DEBUG] FROM pg_catalog.pg_roles
[ldap2pg.psql         DEBUG] WHERE rolname = current_user;
[ldap2pg.manager      WARNI] Running ldap2pg as non superuser.
[ldap2pg.psql         DEBUG] Using Postgres connection to postgresql:///postgres.
[ldap2pg.inspector    DEBUG] Inspecting databases.
[ldap2pg.inspector    DEBUG] Inspecting all defined roles in cluster.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT
[ldap2pg.psql         DEBUG]   role.rolname, array_agg(members.rolname) AS members,
[ldap2pg.psql         DEBUG]   role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit,
[ldap2pg.psql         DEBUG]   pg_catalog.shobj_description(role.oid, 'pg_authid') as comment
[ldap2pg.psql         DEBUG] FROM
[ldap2pg.psql         DEBUG]   pg_catalog.pg_roles AS role
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_auth_members ON roleid = role.oid
[ldap2pg.psql         DEBUG] LEFT JOIN pg_catalog.pg_roles AS members ON members.oid = member
[ldap2pg.psql         DEBUG] GROUP BY role.rolname, role.rolcanlogin, role.rolcreatedb, role.rolcreaterole, role.rolinherit, comment
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Listing managed roles.
[ldap2pg.psql         DEBUG] Doing:
[ldap2pg.psql         DEBUG] SELECT 'public'
[ldap2pg.psql         DEBUG] UNION
[ldap2pg.psql         DEBUG] SELECT DISTINCT role.rolname
[ldap2pg.psql         DEBUG] FROM pg_roles AS role
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_auth_members AS ms ON ms.member = role.oid
[ldap2pg.psql         DEBUG] LEFT OUTER JOIN pg_roles AS ldap_roles
[ldap2pg.psql         DEBUG]   ON ldap_roles.rolname = 'ldap_roles' AND ldap_roles.oid = ms.roleid
[ldap2pg.psql         DEBUG] WHERE role.rolname IN ('ldap_roles', 'readers', 'writers', 'owners')
[ldap2pg.psql         DEBUG]     OR ldap_roles.oid IS NOT NULL
[ldap2pg.psql         DEBUG] ORDER BY 1;
[ldap2pg.inspector    DEBUG] Managing role 'owners' NOCREATEROLE NOCREATEDB NOLOGIN INHERIT.
[ldap2pg.inspector    DEBUG] Managing role 'User1' NOCREATEROLE NOCREATEDB LOGIN INHERIT.
[ldap2pg.inspector    DEBUG] Ignoring role 'postgres'. Matches u'postgres'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_execute_server_program'. Matches u'pg_*'.
[ldap2pg.inspector    DEBUG] Managing role 'writers' NOCREATEROLE NOCREATEDB NOLOGIN INHERIT.
[ldap2pg.inspector    DEBUG] Role 'writers' has members owners.
[ldap2pg.inspector    DEBUG] Managing role 'readers' NOCREATEROLE NOCREATEDB NOLOGIN INHERIT.
[ldap2pg.inspector    DEBUG] Role 'readers' has members writers,User1
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_monitor'. Matches u'pg_*'.
[ldap2pg.inspector    DEBUG] Managing role 'ldap_roles' NOCREATEROLE NOCREATEDB NOLOGIN INHERIT.
[ldap2pg.inspector    DEBUG] Role 'ldap_roles' has members User1
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_signal_backend'. Matches u'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_read_all_settings'. Matches u'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_stat_scan_tables'. Matches u'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'ldap2pg'. Matches u'ldap2pg'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_read_server_files'. Matches u'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'ldapsync'. Matches u'ldapsync'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_read_all_stats'. Matches u'pg_*'.
[ldap2pg.inspector    DEBUG] Ignoring role 'pg_write_server_files'. Matches u'pg_*'.
[ldap2pg.manager      DEBUG] Postgres roles inspection done.
[ldap2pg.manager       INFO] Setup static roles and grants.
[ldap2pg.manager      DEBUG] Want role ldap_roles from YAML.
[ldap2pg.manager      DEBUG] Want role readers from YAML.
[ldap2pg.manager      DEBUG] Want role writers from YAML.
[ldap2pg.manager      DEBUG] Want role owners from YAML.
[ldap2pg.manager      DEBUG] Want GRANT ro on __ALL_DATABASES__.* for * to readers (full) from YAML.
[ldap2pg.manager      DEBUG] Want GRANT rw on __ALL_DATABASES__.* for * to writers (full) from YAML.
[ldap2pg.manager      DEBUG] Want GRANT ddl on __ALL_DATABASES__.* for * to owners (full) from YAML.
[ldap2pg.manager       INFO] Query LDAP to creation of User1 only.
[ldap2pg.manager       INFO] Querying LDAP OU=Users,OU=... (CN=...
[ldap2pg.ldap         DEBUG] Doing: ldapsearch -Y DIGEST-MD5 -U 'ad-user' -W -b OU=Users,OU=someOU,OU=companyUsers,DC=company,DC=com -s sub '(CN=User1)' cn
[ldap2pg.manager      DEBUG] Got 1 entries from LDAP.
[ldap2pg.manager      DEBUG] Want role User1 in LDAP.
[ldap2pg.manager      DEBUG] LDAP inspection completed. Post processing.
[ldap2pg.manager       INFO] Inspecting GRANTs in Postgres cluster...
[ldap2pg.psql         DEBUG] Connecting to Postgres postgresql:postgres.
[ldap2pg.script       ERROR] Unhandled error:
[ldap2pg.script       ERROR] Traceback (most recent call last):
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/script.py", line 37, in main
[ldap2pg.script       ERROR]     exit(synchronize(config))
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/script.py", line 130, in synchronize
[ldap2pg.script       ERROR]     count = manager.sync(syncmap=config['sync_map'])
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/manager.py", line 312, in sync
[ldap2pg.script       ERROR]     schemas = self.inspector.fetch_schemas(databases, ldaproles)
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/inspector.py", line 233, in fetch_schemas
[ldap2pg.script       ERROR]     for dbname, psql in self.psql.itersessions(databases):
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/psql.py", line 86, in itersessions
[ldap2pg.script       ERROR]     with self(dbname) as session:
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/ldap2pg/psql.py", line 156, in __enter__
[ldap2pg.script       ERROR]     self.conn = psycopg2.connect(self.connstring)
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/psycopg2/__init__.py", line 126, in connect
[ldap2pg.script       ERROR]     dsn = _ext.make_dsn(dsn, **kwargs)
[ldap2pg.script       ERROR]   File "/home/ldap2pg/.local/lib/python2.7/site-packages/psycopg2/extensions.py", line 153, in make_dsn
[ldap2pg.script       ERROR]     parse_dsn(dsn)
[ldap2pg.script       ERROR] ProgrammingError: invalid dsn: missing "=" after "postgresql:postgres" in connection info string
[ldap2pg.script       ERROR] Please file an issue at https://github.com/dalibo/ldap2pg/issues with full log.
[ldap2pg.psql         DEBUG] Closing Postgres connexion to postgresql:///postgres.

```

**Comment by bersace** [comment]
Hi @arjan-saly-tfs , I'll take a look at it. We have no commitment on answer delay on GitHub. Usually, I take some days to work on ldap2pg on a monthly basis. So don't worry if an issue is unanswered for a few weeks.

**Comment by bersace** [comment]
Hi @arjan-saly-tfs ,

Can you share me `ldap2pg --version` output ?

`postgresql:///postgres` uses UNIX socket (peer) authentification while `postgresql://localhost:5432/postgres` uses TCP connection and requires a password (unless trust method is used, which is unlikely the case).

ldap2pg 5.8 improved the handling of DSN targeting the different databases in the cluster. I suggest you to upgrade.

Please let me know.

Étienne

**Comment by arjan-saly-tfs** [comment]
Hi @bersace,

Thanks for your answer, it seems like upgrading to 5.8 worked:

Here's the version output:
```~$ ldap2pg --version
ldap2pg 5.8
psycopg2 2.8.6 (dt dec pq3 ext lo64) libpq 11.5
python-ldap 3.3.1
Python 2.7.17 (default, Mar 18 2022, 13:21:42)
[GCC 7.5.0]
```
As I have been deinstalling/reinstalling both ldap2pg and its prerequisites for documentation purposes, I'm not 100% certain this was version on which the issue occurred.

Therefore I re-tested and it _now works as expected_ for postgresql:///postgres .

I assume I was on an older version. The most important thing: It works on 5.8 indeed!
